### ISSUE TITLE
well

### ISSUE THREAD

**Issue by moonljt521** [jp1017/FileExplorer#2]
写的挺好的，就是不维护了

**Comment by jp1017** [comment]
@moonljt521 这个有些丑,md风格的很多了,可以查看这个库: https://github.com/XXApple/AndroidLibs/tree/master/%E5%AE%8C%E6%95%B4%E5%BC%80%E6%BA%90%E9%A1%B9%E7%9B%AEProject

**Comment by moonljt521** [comment]
@jp1017 里边好多项目，你指哪个~  我就是在看管理器相关的项目~~

**Comment by moonljt521** [comment]
看见了 https://github.com/TeamAmaze/AmazeFileManager  是这个吧
